services:
  - type: web
    name: lawyer-profile
    env: go
    region: oregon
    plan: free
    buildCommand: "go mod tidy && go build -o main ./cmd/main"
    startCommand: "./main"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lawyer-db
          property: connectionString

databases:
  - name: lawyer-db
    databaseName: soeeldb
    user: admin
